export const AFFILIATE = 'Affiliate'
export const CAMPAIGN = 'Campaign'
export const DIRECT = 'Direct'
export const INBOUND = 'Inbound Link'
export const INTERNAL = 'Internal Link'
export const SEARCH = 'Search'
export const SOCIAL = 'Social'
export const NA = 'na'