import { Inter } from 'next/font/google'
import './globals.css'
import AnalyticsProviderWrapper from './analytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * Root layout component for the Next.js app
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Page components
 * @returns {JSX.Element}
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnalyticsProviderWrapper>
          {children}
        </AnalyticsProviderWrapper>
      </body>
    </html>
  )
}